[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "airfield"
dynamic = ["version"]
description = "The framework for reproducible robots."
authors = [{ name = "Nathan Tsoi", email = "nathan@vertile.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.9.0",
    "jinja2>=3.1.0",
    "rich>=13.0.0",
    "questionary>=2.0.0",
    "pydantic>=2.0.0",
    "pyyaml>=6.0"
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-mock>=3.10.0",
]

[project.scripts]
airfield = "airfield.main:app"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
airfield = ["templates/docker/*.j2", "templates/tmux/*.j2"]

[tool.setuptools.dynamic]
version = {attr = "airfield.__version__"}
