from pathlib import Path
import xml.etree.ElementTree as ET
from typing import List, Optional, Tuple

import typer
import yaml
from rich.console import Console

from airfield.config import AIRFIELD_CONFIG, dependency_search_paths, find_project_root, packages_dir
from airfield.models import SUPPORTED_ROS_DISTROS
from airfield.docker_cache import generate_dockerignore

console = Console()


# Packages already present in the ROS base images Airfield builds FROM
# (REP 2001 ros_core + ros_base variants). package.xml routinely declares
# these, but they need no dependency manifest: they ship with the image.
# Heuristic prefix/name sets — if a wrap skips something your base actually
# lacks, add a manifest for it and list it in airfield.yaml manually.
_ROS2_BASE_PROVIDED_PREFIXES = (
    "ament_",
    "rcl",
    "rclcpp",
    "rclpy",
    "rosidl_",
    "launch",
    "tf2",
    "ros2",
)
_ROS2_BASE_PROVIDED = {
    "builtin_interfaces",
    "class_loader",
    "common_interfaces",
    "composition_interfaces",
    "console_bridge_vendor",
    "diagnostic_msgs",
    "geometry_msgs",
    "kdl_parser",
    "message_filters",
    "nav_msgs",
    "pluginlib",
    "rcpputils",
    "rcutils",
    "robot_state_publisher",
    "sensor_msgs",
    "sensor_msgs_py",
    "shape_msgs",
    "std_msgs",
    "std_srvs",
    "stereo_msgs",
    "trajectory_msgs",
    "unique_identifier_msgs",
    "urdf",
    "visualization_msgs",
}
_ROS1_BASE_PROVIDED_PREFIXES = ("ros", "tf2", "actionlib")
_ROS1_BASE_PROVIDED = {
    "catkin",
    "diagnostic_msgs",
    "dynamic_reconfigure",
    "geometry_msgs",
    "message_generation",
    "message_runtime",
    "nav_msgs",
    "pluginlib",
    "sensor_msgs",
    "shape_msgs",
    "std_msgs",
    "std_srvs",
    "stereo_msgs",
    "tf",
    "trajectory_msgs",
    "visualization_msgs",
}


def _is_base_provided(dep: str, ros_distro: str) -> bool:
    if ros_distro == "noetic":
        return dep in _ROS1_BASE_PROVIDED or dep.startswith(_ROS1_BASE_PROVIDED_PREFIXES)
    return dep in _ROS2_BASE_PROVIDED or dep.startswith(_ROS2_BASE_PROVIDED_PREFIXES)


def _manifest_exists(dep: str, manifest_root: Path) -> bool:
    """True if any local or shared manifest (any target device) resolves dep."""
    for target in ("arm64", "x86_64"):
        try:
            paths = dependency_search_paths(manifest_root, target)
        except Exception:
            paths = []
        for sp in paths:
            if (sp / f"{dep}.yaml").exists():
                return True
    return False


def _stage_wrap_dependencies(
    ros_deps: List[str],
    ros_distro: str,
    pkg_dir: Path,
    project_root: Optional[Path],
) -> Tuple[List[str], List[str], List[str]]:
    """Sort package.xml deps into (kept, skipped-as-base, generated-manifests).

    Deps with an existing manifest (or a peer package dir) are kept as-is.
    Deps the ROS base image already provides are dropped. For the rest, a
    local xplatform manifest installing ros-<distro>-<dep> via apt is
    generated so the first `package build` resolves instead of erroring —
    marked for review because not every ROS name has a released apt package.
    """
    manifest_root = project_root or pkg_dir
    generated_dir = manifest_root / "dependencies" / "xplatform"

    kept: List[str] = []
    skipped: List[str] = []
    generated: List[str] = []
    for dep in ros_deps:
        if _manifest_exists(dep, manifest_root):
            kept.append(dep)
            continue
        if project_root is not None and (packages_dir(project_root) / dep / AIRFIELD_CONFIG).exists():
            kept.append(dep)  # peer package built from source
            continue
        if _is_base_provided(dep, ros_distro):
            skipped.append(dep)
            continue

        generated_dir.mkdir(parents=True, exist_ok=True)
        apt_pkg = "ros-$ROS_DISTRO-" + dep.replace("_", "-")
        (generated_dir / f"{dep}.yaml").write_text(
            "# Auto-generated by `airfield package init --path` from package.xml.\n"
            f"# REVIEW ME: assumes '{apt_pkg}' exists in the ROS apt repos. If it\n"
            "# doesn't, replace the install command or delete this file and the\n"
            f"# '{dep}' entry in airfield.yaml.\n"
            f"name: {dep}\n"
            "version: 1.0.0\n"
            "system:\n"
            f"  - apt-get update && apt-get install -y {apt_pkg} && rm -rf /var/lib/apt/lists/*\n"
            "user: []\n",
            encoding="utf-8",
        )
        kept.append(dep)
        generated.append(dep)

    return kept, skipped, generated


def _parse_ros2_package_xml(package_xml: Path):
    tree = ET.parse(package_xml)
    root = tree.getroot()

    name_node = root.find("name")
    if name_node is None or not name_node.text:
        raise typer.BadParameter(f"Invalid ROS package.xml at {package_xml}: missing <name>")

    dep_tags = ["depend", "exec_depend", "build_depend", "buildtool_depend", "run_depend"]
    deps = []
    for tag in dep_tags:
        for node in root.findall(tag):
            if node.text:
                deps.append(node.text.strip())

    # Preserve order while deduplicating.
    dep_set = []
    for dep in deps:
        if dep and dep not in dep_set:
            dep_set.append(dep)

    return name_node.text.strip(), dep_set


def _write_airfield_yaml(path: Path, data: dict, force: bool) -> None:
    if path.exists() and not force:
        raise typer.BadParameter(f"{path} already exists. Use --force to overwrite.")
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def _ensure_gitignore_entry(root: Path, entry: str) -> None:
    gitignore = root / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(f"{entry}\n", encoding="utf-8")
        return

    content = gitignore.read_text(encoding="utf-8")
    lines = [line.strip() for line in content.splitlines()]
    if entry in lines:
        return

    suffix = "" if content.endswith("\n") or not content else "\n"
    gitignore.write_text(f"{content}{suffix}{entry}\n", encoding="utf-8")


def _project_ros_distro(project_root: Optional[Path]) -> str:
    if project_root is None:
        return "jazzy"

    project_yaml = project_root / AIRFIELD_CONFIG
    if not project_yaml.exists():
        return "jazzy"

    try:
        data = yaml.safe_load(project_yaml.read_text(encoding="utf-8"))
    except Exception:
        return "jazzy"

    if isinstance(data, dict):
        ros_distro = data.get("ros_distro")
        if isinstance(ros_distro, str) and ros_distro.strip():
            return ros_distro.strip().lower()

    return "jazzy"


def _is_path_like(value: str) -> bool:
    if value in {".", ".."}:
        return True
    if "/" in value or "\\" in value:
        return True
    return Path(value).exists()


def _init_new_package(name: str, force: bool, ros_distro: str) -> None:
    project_root = find_project_root()

    if project_root is not None and not _is_path_like(name):
        pkg_dir = packages_dir(project_root) / name
        package_name = name
    else:
        pkg_dir = Path(name).expanduser().resolve()
        package_name = pkg_dir.name

    pkg_dir.mkdir(parents=True, exist_ok=True)
    (pkg_dir / "src").mkdir(parents=True, exist_ok=True)

    package_yaml = {
        "kind": "package",
        "name": package_name,
        "dependencies": [],
        "source_path": "src",
        "ros_distro": ros_distro,
    }

    _write_airfield_yaml(pkg_dir / AIRFIELD_CONFIG, package_yaml, force=force)

    readme_path = pkg_dir / "README.md"
    if not readme_path.exists():
        readme_path.write_text(
            f"# {package_name}\n\nAirfield package scaffold. Place ROS code under ./src\n",
            encoding="utf-8",
        )

    _ensure_gitignore_entry(pkg_dir, ".air")
    _ensure_gitignore_entry(pkg_dir, ".airfield/")
    _ensure_gitignore_entry(pkg_dir, "build/")
    _ensure_gitignore_entry(pkg_dir, "log/")
    _ensure_gitignore_entry(pkg_dir, "install/")

    # Generate .dockerignore for optimized container builds
    generate_dockerignore(pkg_dir)

    console.print(f"[bold green]Initialized Airfield package {package_name} at {pkg_dir}[/bold green]")


def _wrap_existing_ros_package(path: Path, force: bool, ros_distro: str) -> None:
    pkg_dir = path.resolve()
    package_xml = pkg_dir / "package.xml"
    if not package_xml.exists():
        raise typer.BadParameter(f"Expected package.xml at {package_xml}")

    pkg_name, ros_deps = _parse_ros2_package_xml(package_xml)
    kept_deps, base_deps, generated_deps = _stage_wrap_dependencies(
        ros_deps, ros_distro, pkg_dir, find_project_root(pkg_dir)
    )

    package_yaml = {
        "kind": "package",
        "name": pkg_name,
        "dependencies": kept_deps,
        "source_path": ".",
        "ros_distro": ros_distro,
    }

    _write_airfield_yaml(pkg_dir / AIRFIELD_CONFIG, package_yaml, force=force)

    airfield_note = pkg_dir / "AIRFIELD.md"
    if not airfield_note.exists():
        airfield_note.write_text(
            "# Airfield Notes\n\n"
            "This ROS package has been wrapped for Airfield.\n"
            "- airfield.yaml defines Airfield package metadata\n"
            "- source_path is '.' so Airfield builds from this package root\n",
            encoding="utf-8",
        )

    _ensure_gitignore_entry(pkg_dir, ".air")
    _ensure_gitignore_entry(pkg_dir, ".airfield/")
    _ensure_gitignore_entry(pkg_dir, "build/")
    _ensure_gitignore_entry(pkg_dir, "log/")
    _ensure_gitignore_entry(pkg_dir, "install/")

    # Generate .dockerignore for optimized container builds
    generate_dockerignore(pkg_dir)

    console.print(f"[bold green]Wrapped existing ROS package at {pkg_dir}[/bold green]")
    if base_deps:
        console.print(
            f"Omitted {len(base_deps)} dependencies the ROS base image already provides: "
            f"{', '.join(base_deps)}"
        )
    if generated_deps:
        console.print(
            f"[yellow]Generated {len(generated_deps)} local dependency manifest(s) under "
            f"dependencies/xplatform/: {', '.join(generated_deps)}[/yellow]"
        )
        console.print(
            "[yellow]Each assumes an apt package named ros-<distro>-<name> exists — review them, "
            "then upstream with `airfield package dependencies upstream .`[/yellow]"
        )


def run(
    name: Optional[str] = typer.Argument(None, help="New package name (omit when using --path for existing ROS package)"),
    path: Optional[Path] = typer.Option(None, "--path", help="Path to existing ROS package to wrap in place"),
    ros_distro: Optional[str] = typer.Option(None, "--ros-distro", help="ROS distribution for the package workspace (noetic, humble, or jazzy)"),
    force: bool = typer.Option(False, "--force", help="Overwrite existing airfield.yaml if present"),
):
    """Initialize a new Airfield package or wrap an existing ROS package."""
    project_root = find_project_root()
    resolved_ros_distro = (ros_distro or _project_ros_distro(project_root)).strip().lower()
    if resolved_ros_distro not in SUPPORTED_ROS_DISTROS:
        raise typer.BadParameter(
            f"Unsupported ROS distribution '{resolved_ros_distro}'. Supported values: {', '.join(sorted(SUPPORTED_ROS_DISTROS))}"
        )

    if path is not None:
        if name is not None:
            raise typer.BadParameter("Do not pass a package name when using --path.")
        _wrap_existing_ros_package(path, force=force, ros_distro=resolved_ros_distro)
        return

    if name is None:
        raise typer.BadParameter("Package name is required unless --path is provided.")

    _init_new_package(name, force=force, ros_distro=resolved_ros_distro)
