import os
import pwd
import shlex
import shutil
import subprocess
import tempfile
from importlib import metadata as importlib_metadata
from pathlib import Path
from typing import List, Optional, Tuple

from airfield.models import Dependency, Package, ROS_DISTROS
from airfield.build_progress import run_build_with_progress, with_plain_progress
from airfield.docker_cache import get_cache_optimization_comment
from airfield.config import is_arm_mac


DOCKER_PLATFORMS = {
    "arm64": "linux/arm64",
    "aarch64": "linux/arm64",
    "x86_64": "linux/amd64",
    "amd64": "linux/amd64",
}

UBUNTU_BASE_IMAGE = "ubuntu:24.04"

# Baked into every ROS image at /opt/airfield-entry.sh and used by
# `package cmd` / `package run` as the container command wrapper. Ensures the
# target colcon package is built into the shared ~/workspace/install before the
# real command runs, then hands off to a login shell (whose profile sources ROS
# + the workspace overlay). Skips the build when the package has no colcon
# source in ~/workspace/src (apt-only/tool packages), or is already built.
# Concurrent containers serialize on a flock in the shared log/ dir so only one
# colcon build runs at a time (a Jetson-class host OOMs on parallel builds);
# make/cmake parallelism defaults are derived from the host (cores, capped by
# ~4GB RAM per compile job so memory-lean boards like Jetsons don't OOM) and
# can be overridden via MAKEFLAGS / CMAKE_BUILD_PARALLEL_LEVEL.
ENTRY_SCRIPT = """#!/bin/bash
# Generated by airfield (builder.py ENTRY_SCRIPT). Do not edit in-container.
# Usage: /opt/airfield-entry.sh '<command string>'
# Env:  AIRFIELD_BUILD_PKG    colcon package to ensure is built (empty = skip)
#       AIRFIELD_COLCON_ARGS  extra args appended to `colcon build`
# NOTE: no `set -u` here — ROS setup.bash is not nounset-clean
# (AMENT_TRACE_SETUP_FILES: unbound variable) and would abort the source.
pkg="${AIRFIELD_BUILD_PKG:-}"
ws="$HOME/workspace"
if [ -n "$pkg" ] && [ -n "${ROS_DISTRO:-}" ] \\
    && [ -f "/opt/ros/$ROS_DISTRO/setup.bash" ] && [ -d "$ws/src" ]; then
    (
        source "/opt/ros/$ROS_DISTRO/setup.bash"
        cd "$ws" || exit 1
        mkdir -p build install log
        if command -v colcon >/dev/null 2>&1 \\
            && colcon list -n 2>/dev/null | grep -qx "$pkg" \\
            && [ ! -e "install/$pkg" ]; then
            echo "[airfield-entry] building '$pkg' into $ws/install (first run)..."
            # Default build parallelism: one job per core, capped by ~4GB RAM
            # per job (protects memory-lean boards; big hosts get full cores).
            cores=$(nproc 2>/dev/null || echo 2)
            mem_kb=$(awk '/MemTotal/ {print $2}' /proc/meminfo 2>/dev/null || echo 8388608)
            mem_jobs=$(( mem_kb / 4194304 ))
            [ "$mem_jobs" -lt 1 ] && mem_jobs=1
            jobs=$(( cores < mem_jobs ? cores : mem_jobs ))
            export MAKEFLAGS="${MAKEFLAGS:--j$jobs}"
            export CMAKE_BUILD_PARALLEL_LEVEL="${CMAKE_BUILD_PARALLEL_LEVEL:-$jobs}"
            # shellcheck disable=SC2086
            flock log/.airfield_build.lock \\
                colcon build --packages-up-to "$pkg" --parallel-workers 1 \\
                ${AIRFIELD_COLCON_ARGS:-}
        fi
    ) || { echo "[airfield-entry] build of '$pkg' failed; not running command" >&2; exit 1; }
fi
exec /bin/bash -lc "${1:?airfield-entry: missing command}"
"""

# Baked into every image at /opt/airfield-pip-check.sh and run twice during the
# build: once to record which distributions the base image already ships broken,
# once at the end to fail if the package's own installs broke a new one.
#
# Batching every `pip:` requirement into a single install lets pip's resolver
# find a mutually-consistent set, but it only covers what went through that one
# install. Three things sit outside it and can still collide: apt-installed
# Python packages (most dependency manifests are apt), manifests that must run
# their own pip command (a custom index, a GPU/CPU branch), and whatever the
# base image shipped. `pip check` reads everything importable, so it catches the
# seams the batched resolve structurally cannot.
#
# The baseline subtraction matters for portability: Airfield builds on arbitrary
# vendor base images, and a conflict that arrived with the base image is not the
# package author's to fix. Failing on it would make Airfield unusable on stacks
# whose images the developer does not control.
PIP_CHECK_SCRIPT = """#!/bin/sh
# Generated by airfield (builder.py PIP_CHECK_SCRIPT). Do not edit in-container.
# Usage: airfield-pip-check.sh baseline <path>
#        airfield-pip-check.sh verify   <path> <strict|warn>
set -u

mode="${1:?airfield-pip-check: missing mode}"
baseline="${2:?airfield-pip-check: missing baseline path}"

# Names of distributions whose requirements are currently unsatisfied, sorted
# and deduped so the baseline can be subtracted with comm(1).
broken_names() {
    python3 -m pip check 2>/dev/null \\
        | grep -v '^No broken requirements found' \\
        | awk 'NF {print $1}' \\
        | sort -u
}

case "$mode" in
baseline)
    broken_names > "$baseline" 2>/dev/null || : > "$baseline"
    ;;
verify)
    strict="${3:-strict}"
    [ -f "$baseline" ] || : > "$baseline"
    introduced=$(broken_names | comm -13 "$baseline" -)
    [ -n "$introduced" ] || exit 0

    echo "" >&2
    echo "[airfield] Dependency conflict introduced by this package's installs:" >&2
    python3 -m pip check 2>/dev/null | while IFS= read -r line; do
        for name in $introduced; do
            case "$line" in "$name "*) echo "    $line" >&2 ;; esac
        done
    done
    echo "" >&2
    echo "[airfield] These share one Python environment. Something installed outside" >&2
    echo "[airfield] the batched resolve -- an apt manifest, a manifest running its own" >&2
    echo "[airfield] pip command, or the base image -- replaced a version another" >&2
    echo "[airfield] package needs. Moving the conflicting installs into 'pip:' entries" >&2
    echo "[airfield] lets pip solve them together." >&2
    if [ "$strict" = "warn" ]; then
        echo "[airfield] Continuing anyway (AIRFIELD_PIP_CHECK=warn)." >&2
        exit 0
    fi
    echo "[airfield] Set AIRFIELD_PIP_CHECK=warn to continue anyway, or =off to skip." >&2
    exit 1
    ;;
*)
    echo "airfield-pip-check: unknown mode '$mode'" >&2
    exit 2
    ;;
esac
"""

PIP_BASELINE_PATH = "/opt/airfield-pip-baseline.txt"


class Builder:
    def __init__(self, package: Package, dependencies: List[Dependency], target_device: str):
        self.package = package
        self.dependencies = dependencies
        self.target_device = target_device
        self.ros_distro = self._resolve_ros_distro()
        self.base_image = self._resolve_base_image()

    def _resolve_ros_distro(self) -> Optional[str]:
        if self.package.ros_distro is None:
            return None

        ros_distro = self.package.ros_distro.strip().lower()
        if not ros_distro:
            return None
        if ros_distro not in ROS_DISTROS:
            raise ValueError(
                f"Unsupported ROS distribution '{ros_distro}'. Supported values: {', '.join(sorted(ROS_DISTROS))}"
            )
        return ros_distro

    def _resolve_base_image(self) -> str:
        if self.package.base_image:
            return self.package.base_image
        if self.ros_distro:
            distro = ROS_DISTROS[self.ros_distro]
            if self.target_device.strip().lower() in {"arm64", "aarch64"}:
                return distro["arm64_base_image"]
            return distro["base_image"]
        return UBUNTU_BASE_IMAGE

    def _resolve_docker_platform(self) -> Optional[str]:
        return DOCKER_PLATFORMS.get(self.target_device.strip().lower())

    def _find_airfield_repo(self, context_dir: Path) -> Optional[Path]:
        # Candidates for the airfield repository root:
        # 1. The context directory and its parents
        # 2. The directory where the airfield source code resides (3 levels up from this file: src/airfield/builder.py)
        candidates = [context_dir, *context_dir.parents]
        try:
            candidates.append(Path(__file__).resolve().parents[2])
        except (IndexError, ValueError):
            pass

        for candidate in candidates:
            if not candidate.exists():
                continue
            # Check if the candidate itself is the repo root
            if (candidate / "pyproject.toml").exists() and (candidate / "src" / "airfield").exists():
                return candidate
            # Check if there is an 'airfield' subdirectory that is the repo root
            repo_root = candidate / "airfield"
            if repo_root.exists() and (repo_root / "pyproject.toml").exists() and (repo_root / "src" / "airfield").exists():
                return repo_root
        return None

    def _airfield_runtime_requirements(self) -> List[str]:
        """Runtime requirements of the installed airfield distribution.

        Read from installed metadata so the synthesized project matches whatever
        this CLI was installed with; extras (test-only deps) are filtered out.
        """
        fallback = [
            "typer>=0.9.0",
            "jinja2>=3.1.0",
            "rich>=13.0.0",
            "questionary>=2.0.0",
            "pydantic>=2.0.0",
            "pyyaml>=6.0",
        ]
        try:
            reqs = importlib_metadata.requires("airfield") or []
        except Exception:
            return fallback
        runtime = [r for r in reqs if "extra ==" not in r]
        return runtime or fallback

    def _stage_airfield_source(self, context_dir: Path, build_root: Path) -> None:
        """Stage the running airfield CLI into the build context at build_root/airfield.

        The image must run THIS airfield, never `pip install airfield` from PyPI:
        the PyPI name is owned by an unrelated project ("AirField", a pydantic
        forms library), so a registry install puts wrong third-party code in
        every image. When a source checkout is visible (developer install) copy
        it; otherwise reconstruct an installable project from the imported
        package so pipx/venv installs work identically.
        """
        airfield_repo = self._find_airfield_repo(context_dir)
        if airfield_repo is not None:
            shutil.copytree(
                airfield_repo,
                build_root / "airfield",
                ignore=shutil.ignore_patterns(".git", "__pycache__", "*.pyc", "build", "dist", "*.egg-info"),
            )
            return

        import airfield as airfield_pkg

        pkg_src = Path(airfield_pkg.__file__).resolve().parent
        dest_root = build_root / "airfield"
        shutil.copytree(
            pkg_src,
            dest_root / "src" / "airfield",
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
        )

        version = getattr(airfield_pkg, "__version__", "0.0.0")
        requirements = ",\n    ".join(f'"{req}"' for req in self._airfield_runtime_requirements())
        (dest_root / "pyproject.toml").write_text(
            f"""[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "airfield"
version = "{version}"
description = "The framework for reproducible robots."
requires-python = ">=3.10"
dependencies = [
    {requirements}
]

[project.scripts]
airfield = "airfield.main:app"

[tool.setuptools]
package-dir = {{"" = "src"}}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
airfield = ["templates/docker/*.j2", "templates/tmux/*.j2"]
""",
            encoding="utf-8",
        )

    def _supports_cache_mounts(self) -> bool:
        if is_arm_mac():
            return True
        # Manual override for troubleshooting/CI:
        # AIRFIELD_FORCE_DOCKER_CACHE_MOUNTS=1 -> enable
        # AIRFIELD_DISABLE_DOCKER_CACHE_MOUNTS=1 -> disable
        force = (os.environ.get("AIRFIELD_FORCE_DOCKER_CACHE_MOUNTS") or "").strip().lower()
        if force in {"1", "true", "yes", "on"}:
            return True

        disable = (os.environ.get("AIRFIELD_DISABLE_DOCKER_CACHE_MOUNTS") or "").strip().lower()
        if disable in {"1", "true", "yes", "on"}:
            return False

        try:
            result = subprocess.run(
                ["docker", "--version"],
                capture_output=True,
                text=True,
                check=False,
            )
        except FileNotFoundError:
            return False

        version_text = f"{result.stdout}\n{result.stderr}".lower()
        if "podman" in version_text or "buildah" in version_text:
            return False

        try:
            buildx_result = subprocess.run(
                ["docker", "buildx", "version"],
                capture_output=True,
                text=True,
                check=False,
            )
        except FileNotFoundError:
            self._print_buildkit_hint("docker buildx was not found")
            return False

        if buildx_result.returncode != 0:
            details = (buildx_result.stderr or buildx_result.stdout or "docker buildx version failed").strip()
            self._print_buildkit_hint(details)
            return False
        return True

    def _print_buildkit_hint(self, details: str) -> None:
        print("[WARN] Docker Buildx/BuildKit is not available; using compatibility mode.")
        if details:
            print(f"[WARN] Buildx check: {details}")
        print("[WARN] Install or enable Docker Buildx/BuildKit to use Airfield cache mounts.")

    def _apt_install_command(self, packages: List[str], cache_mounts_enabled: bool) -> str:
        command = "apt-get update && apt-get install -y " + " ".join(packages)
        if not cache_mounts_enabled:
            command += " && rm -rf /var/lib/apt/lists/*"
        return command

    def _pip_check_mode(self) -> str:
        """How a newly-introduced pip conflict is handled: strict|warn|off."""
        raw = (os.environ.get("AIRFIELD_PIP_CHECK") or "").strip().lower()
        if raw in {"off", "0", "false", "no", "none"}:
            return "off"
        if raw in {"warn", "warning", "soft"}:
            return "warn"
        return "strict"

    def _batched_apt_packages(self) -> List[str]:
        """Every dependency's `apt:` packages, in declaration order, deduped."""
        packages: List[str] = []
        seen = set()
        for dep in self.dependencies:
            for name in dep.apt:
                if name not in seen:
                    seen.add(name)
                    packages.append(name)
        return packages

    def _batched_pip_specs(self) -> List[str]:
        """Every dependency's `pip:` requirements, in declaration order, deduped.

        Order is stable so the generated Dockerfile (and therefore the layer
        cache) does not churn between builds. Duplicates are dropped rather than
        passed twice; pip accepts repeats, but a package listing both `numpy`
        and something that also declares `numpy` should produce one clean spec.
        """
        specs: List[str] = []
        seen = set()
        for dep in self.dependencies:
            for spec in dep.pip:
                if spec not in seen:
                    seen.add(spec)
                    specs.append(spec)
        return specs

    def _pip_install_command(self, specs: List[str]) -> str:
        """One `pip install` for every batched requirement.

        Specs are shell-quoted: version constraints contain '<' and '>', which
        an unquoted shell would read as redirections. The --break-system-packages
        retry mirrors the pip-upgrade step above -- the flag is required on PEP
        668 distros (Ubuntu 24.04+) and unknown to pip older than 23.0.1, and
        Airfield has to build on both.
        """
        quoted = " ".join(shlex.quote(spec) for spec in specs)
        return (
            f"python3 -m pip install --break-system-packages {quoted} || \\\n"
            f"    python3 -m pip install {quoted}"
        )

    def generate_dockerfile(self, cache_mounts_enabled: bool = True) -> str:
        lines = []
        default_uid = os.getuid()
        default_gid = os.getgid()
        default_username = pwd.getpwuid(default_uid).pw_name
        
        # Add optimization comment at the top
        lines.append(get_cache_optimization_comment(cache_mounts_enabled=cache_mounts_enabled))
        lines.append("")
        
        lines.append(f"FROM {self.base_image}")
        lines.append("USER root")
        lines.append("ENV DEBIAN_FRONTEND=noninteractive")
        if self.ros_distro:
            lines.append(f"ENV ROS_DISTRO={self.ros_distro}")
        lines.append("ARG TORCH_INSTALL_TARGET=cpu")
        lines.append("ARG TORCH_VERSION=")
        lines.append("ARG TORCH_GPU_WHL_TAG=cu121")
        if is_arm_mac():
            lines.append("RUN echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4")
        
        # Optimized apt-get with BuildKit cache mounts.
        # Keep this minimal: anything beyond pip/git belongs in dependency
        # manifests so packages only pay for what they declare (python3-opencv
        # alone used to drag Qt/GStreamer into every image).
        base_packages = ["python3-pip", "git"]
        if self.ros_distro:
            base_packages.extend(ROS_DISTROS[self.ros_distro]["core_packages"])
        apt_install = self._apt_install_command(base_packages, cache_mounts_enabled=cache_mounts_enabled)
        if cache_mounts_enabled:
            lines.append(
                "RUN --mount=type=cache,target=/var/lib/apt,sharing=locked \\\n"
                "    --mount=type=cache,target=/var/cache/apt,sharing=locked \\\n"
                f"    {apt_install}"
            )
        else:
            lines.append(f"RUN {apt_install}")

        # Upgrading pip is best-effort: on PEP 668 distros (e.g. Ubuntu 24.04) the
        # system pip is debian-managed and may refuse to upgrade. Don't fail the
        # build over it; the existing pip is sufficient.
        if cache_mounts_enabled:
            lines.append(
                "RUN --mount=type=cache,target=/root/.cache/pip \\\n"
                "    python3 -m pip install --break-system-packages --upgrade pip || \\\n"
                "    python3 -m pip install --upgrade pip || true"
            )
        else:
            lines.append(
                "RUN python3 -m pip install --break-system-packages --upgrade pip || "
                "python3 -m pip install --upgrade pip || true"
            )

        # Install the airfield CLI staged into the build context by
        # _stage_airfield_source. Never install "airfield" from PyPI: that name
        # belongs to an unrelated third-party project.
        lines.append("COPY airfield /opt/airfield")
        if cache_mounts_enabled:
            lines.append(
                "RUN --mount=type=cache,target=/root/.cache/pip \\\n"
                "    python3 -m pip install /opt/airfield || \\\n"
                "    python3 -m pip install --break-system-packages /opt/airfield"
            )
        else:
            lines.append(
                "RUN python3 -m pip install --no-cache-dir /opt/airfield || "
                "python3 -m pip install --no-cache-dir --break-system-packages /opt/airfield"
            )

        pip_check_mode = self._pip_check_mode()
        if pip_check_mode != "off":
            # Placed directly after the airfield CLI install, which already busts
            # the cache below it whenever airfield's source changes, so this COPY
            # costs no extra layer invalidation. The baseline must be recorded
            # before any dependency install runs: everything broken from here on
            # is attributable to this package.
            lines.append("COPY airfield-pip-check.sh /opt/airfield-pip-check.sh")
            lines.append("RUN chmod 755 /opt/airfield-pip-check.sh")
            lines.append(f"RUN /opt/airfield-pip-check.sh baseline {PIP_BASELINE_PATH}")

        # One install for every batched apt package, before the escape-hatch
        # commands below. A manifest that must add a third-party repository has
        # to keep both the repo setup and its install in `system:`, since the
        # batch runs first and would not see the new source.
        apt_packages = self._batched_apt_packages()
        if apt_packages:
            dep_apt_install = self._apt_install_command(
                apt_packages, cache_mounts_enabled=cache_mounts_enabled
            )
            if cache_mounts_enabled:
                lines.append(
                    "RUN --mount=type=cache,target=/var/lib/apt,sharing=locked \\\n"
                    "    --mount=type=cache,target=/var/cache/apt,sharing=locked \\\n"
                    f"    {dep_apt_install}"
                )
            else:
                lines.append(f"RUN {dep_apt_install}")

        system_cmds = []
        for dep in self.dependencies:
            system_cmds.extend(dep.system)

        if system_cmds:
            for cmd in system_cmds:
                # Optimize apt-get commands in system dependencies
                if cmd.startswith("apt-get") or "apt-get" in cmd:
                    if "apt-get update" in cmd and cache_mounts_enabled:
                        lines.append(f"RUN --mount=type=cache,target=/var/lib/apt,sharing=locked \\\n    --mount=type=cache,target=/var/cache/apt,sharing=locked \\\n    {cmd}")
                    else:
                        lines.append(f"RUN {cmd}")
                elif "pip" in cmd and "install" in cmd and cache_mounts_enabled:
                    lines.append(f"RUN --mount=type=cache,target=/root/.cache/pip \\\n    {cmd}")
                else:
                    lines.append(f"RUN {cmd}")

        lines.append(f"ARG USERNAME={default_username}")
        lines.append(f"ARG UID={default_uid}")
        lines.append(f"ARG GID={default_gid}")
        lines.append(
            "RUN set -e && "
            "(getent group $GID || groupadd -g $GID $USERNAME) >/dev/null && "
            "if id -u $UID >/dev/null 2>&1; then "
            "existing_user=$(id -nu $UID) && "
            "usermod -l $USERNAME -d /home/$USERNAME -m $existing_user 2>/dev/null || true && "
            "usermod -g $GID $USERNAME 2>/dev/null || true; "
            "else "
            "useradd --uid $UID --gid $GID -m $USERNAME; "
            "fi"
        )
        lines.append("RUN git config --system --add safe.directory '*'")
        lines.append("RUN mkdir -p /home/$USERNAME/workspace/src && chown -R $UID:$GID /home/$USERNAME")
        if self.ros_distro:
            lines.append(
                "RUN printf '%s\\n' 'source /opt/ros/$ROS_DISTRO/setup.bash' >> /home/$USERNAME/.bashrc && "
                "printf '%s\\n' 'if [ -f $HOME/workspace/install/setup.bash ]; then source $HOME/workspace/install/setup.bash; fi' >> /home/$USERNAME/.bashrc && "
                "printf '%s\\n' 'colcon_build() { mkdir -p log && colcon build \"$@\"; }' >> /home/$USERNAME/.bashrc && "
                "printf '%s\\n' 'source /opt/ros/$ROS_DISTRO/setup.bash' >> /home/$USERNAME/.profile && "
                "printf '%s\\n' 'if [ -f $HOME/workspace/install/setup.bash ]; then source $HOME/workspace/install/setup.bash; fi' >> /home/$USERNAME/.profile"
            )
            # Build-if-needed command wrapper used by `package cmd`/`package run`.
            lines.append("COPY airfield-entry.sh /opt/airfield-entry.sh")
            lines.append("RUN chmod 755 /opt/airfield-entry.sh")

        lines.append("USER $USERNAME")
        lines.append("ENV HOME=/home/$USERNAME")
        lines.append("WORKDIR /home/$USERNAME/workspace")

        # One install for every batched requirement, before the escape-hatch
        # commands below. Manifests that run their own pip command are doing
        # something deliberate (a CUDA wheel index, a GPU/CPU branch), so they
        # get the last word over the generic resolve.
        pip_specs = self._batched_pip_specs()
        if pip_specs:
            pip_install = self._pip_install_command(pip_specs)
            if cache_mounts_enabled:
                lines.append(
                    "RUN --mount=type=cache,target=/home/$USERNAME/.cache/pip \\\n"
                    f"    {pip_install}"
                )
            else:
                lines.append(f"RUN {pip_install}")

        user_cmds = []
        for dep in self.dependencies:
            user_cmds.extend(dep.user)

        if user_cmds:
            for cmd in user_cmds:
                # Optimize pip commands in user dependencies
                if "pip" in cmd and "install" in cmd and cache_mounts_enabled:
                    lines.append(f"RUN --mount=type=cache,target=/home/$USERNAME/.cache/pip \\\n    {cmd}")
                else:
                    lines.append(f"RUN {cmd}")

        if pip_check_mode != "off":
            # Runs as $USERNAME, matching the user-phase installs: unprivileged
            # pip falls back to ~/.local, which root's view of the environment
            # would not see.
            lines.append(
                f"RUN /opt/airfield-pip-check.sh verify {PIP_BASELINE_PATH} {pip_check_mode}"
            )

        lines.append("ENV IN_AIRFIELD_CONTAINER=1")

        return "\n".join(lines)

    def build(self, context_dir: Path, show_all_output: bool = False) -> Tuple[bool, str]:
        # Docker output now streams by default; keep this parameter for CLI compatibility.
        del show_all_output

        image_name = f"airfield-pkg-{self.package.name}:latest"

        with tempfile.TemporaryDirectory() as td:
            build_root = Path(td)
            cache_mounts_enabled = self._supports_cache_mounts()
            self._stage_airfield_source(context_dir, build_root)

            # Always present in the build context; only COPY'd into ROS images
            # (see generate_dockerfile's ros_distro block).
            (build_root / "airfield-entry.sh").write_text(ENTRY_SCRIPT, encoding="utf-8")

            # Likewise staged unconditionally; COPY'd unless AIRFIELD_PIP_CHECK=off.
            (build_root / "airfield-pip-check.sh").write_text(PIP_CHECK_SCRIPT, encoding="utf-8")

            local_dependency_root = context_dir / "dependencies" / self.target_device
            if local_dependency_root.exists() and any(local_dependency_root.glob("**/*.yaml")):
                print("[WARN] Local dependency manifests were found in the source tree.")
                print("[WARN] Please upstream them to the packages repository instead of keeping them local.")
                print("[WARN] Repo: https://github.com/airfield/packages")
                print("[WARN] README: https://github.com/airfield/packages#readme")
                print("[WARN] Command: airfield package dependencies upstream .")

            dockerfile_content = self.generate_dockerfile(
                cache_mounts_enabled=cache_mounts_enabled,
            )
            df_path = build_root / "Dockerfile"
            df_path.write_text(dockerfile_content, encoding="utf-8")

            uid = str(os.getuid())
            gid = str(os.getgid())
            username = pwd.getpwuid(os.getuid()).pw_name

            if is_arm_mac():
                container_archs = {
                    "arm64": "arm64",
                    "aarch64": "arm64",
                    "x86_64": "amd64",
                    "amd64": "amd64",
                }
                cmd = [
                    "container", "build",
                    "--arch", container_archs.get(self.target_device.strip().lower(), "arm64"),
                    "--build-arg", f"UID={uid}",
                    "--build-arg", f"GID={gid}",
                    "--build-arg", f"USERNAME={username}",
                    "-t", image_name,
                    "-f", str(df_path),
                    str(build_root),
                ]
            else:
                # `--pull` always refreshes the base image from a registry. Skip it
                # when AIRFIELD_NO_PULL is set so packages can use a locally-built
                # base image (e.g. a custom L4T base) that is not in any registry.
                no_pull = os.environ.get("AIRFIELD_NO_PULL", "").strip().lower() in {"1", "true", "yes"}
                cmd = [
                    "docker", "build",
                    "--network", "host",
                    "--platform", self._resolve_docker_platform() or self.target_device,
                    *([] if no_pull else ["--pull"]),
                    "--build-arg", f"UID={uid}",
                    "--build-arg", f"GID={gid}",
                    "--build-arg", f"USERNAME={username}",
                    "-t", image_name,
                    "-f", str(df_path),
                    str(build_root),
                ]

            torch_build_args = [
                ("TORCH_INSTALL_TARGET", "AIRFIELD_TORCH_INSTALL_TARGET"),
                ("TORCH_VERSION", "AIRFIELD_TORCH_VERSION"),
                ("TORCH_GPU_WHL_TAG", "AIRFIELD_TORCH_GPU_WHL_TAG"),
            ]
            for docker_arg, preferred_host_env in torch_build_args:
                value = os.environ.get(preferred_host_env)
                if value is None:
                    value = os.environ.get(docker_arg)
                if value:
                    cmd.extend(["--build-arg", f"{docker_arg}={value}"])

            # Enable BuildKit for optimized caching
            env = os.environ.copy()
            if cache_mounts_enabled:
                env["DOCKER_BUILDKIT"] = "1"
            else:
                env.pop("DOCKER_BUILDKIT", None)

            # Surface every env-driven toggle that changed this build, so
            # behavior differences between machines are visible instead of
            # silently coming from someone's shell profile.
            toggles = [
                f"engine={'container' if is_arm_mac() else 'docker'}",
                f"platform={self._resolve_docker_platform() or self.target_device}",
                f"base_image={self.base_image}",
                f"cache_mounts={'on' if cache_mounts_enabled else 'off'}",
            ]
            if not is_arm_mac():
                toggles.append("pull=skipped (AIRFIELD_NO_PULL set)" if no_pull else "pull=always")
            for docker_arg, preferred_host_env in torch_build_args:
                for env_name in (preferred_host_env, docker_arg):
                    if os.environ.get(env_name):
                        toggles.append(f"{docker_arg}={os.environ[env_name]} (from ${env_name})")
                        break
            print(f"[airfield] build settings: {'  '.join(toggles)}")
            print(f"Executing: {' '.join(cmd)}")
            print("--- Dockerfile ---")
            print(dockerfile_content)
            print("------------------")

            print("Container is building. This can take a few minutes...")
            if cache_mounts_enabled:
                print("(BuildKit cache mounts enabled for optimized rebuilds)")
            else:
                print("(Cache mounts disabled for this engine; using compatibility mode)")
            result = run_build_with_progress(
                cmd=with_plain_progress(cmd) if cache_mounts_enabled else cmd,
                cwd=str(context_dir),
                env=env,
                image_name=image_name,
            )

            if result.returncode != 0 and cache_mounts_enabled:
                stderr_text = (result.stderr or "").lower()
                stdout_text = (result.stdout or "").lower()
                if "invalid mount type \"cache\"" in stderr_text or "invalid mount type \"cache\"" in stdout_text:
                    print("Build engine rejected cache mounts. Retrying in compatibility mode...")
                    dockerfile_content = self.generate_dockerfile(
                        cache_mounts_enabled=False,
                    )
                    df_path.write_text(dockerfile_content, encoding="utf-8")
                    env = os.environ.copy()
                    env.pop("DOCKER_BUILDKIT", None)
                    print("--- Dockerfile (compatibility mode) ---")
                    print(dockerfile_content)
                    print("----------------------------------------")
                    result = run_build_with_progress(
                        cmd=cmd,
                        cwd=str(context_dir),
                        env=env,
                        image_name=image_name,
                    )

            if result.returncode != 0:
                return False, image_name

            return True, image_name
